### ISSUE TITLE
Modderstroom

### ISSUE THREAD

**Issue by gezever** [Informatievlaanderen/OSLOthema-modderstromen#13]
Het kan zijn dat ik erover heb gezien, maar ik zie nergens een klasse modderstroom, noch een veroorzaker van de modderstroom. In een use-case van voorspelling lijkt me dit toch relevant.

**Comment by pheyvaer** [comment]
De scope van deze track is beperkt tot de maatregelen die erosie bestrijden. Modderstromen en het beschrijven ervan is niet in scope.
