### ISSUE TITLE
sosa:phenomenonTime vs prov:startedAtTime/endedAtTime

### ISSUE THREAD

**Issue by pheyvaer** [Informatievlaanderen/OSLOthema-modderstromen#25]

**Comment by gezever** [comment]
### Literals, (dataTime) vs. Class (instances) 
Binnen het kader van het ssn/sosa - prov-o alignment zijn er twee formaten met een verschillende finaliteit om een tijdsaanduiding weer te geven i.v.m. prov-o Activiteiten en de subclasses hiervan in SOSA.

1.  Tijdsaanduidingen die over het moment van de actuatie, sampling of observatie gaan (soorten activiteiten). (en als range een rdfs:Literal hebben,  cfr. KISS_principle)

```turtle
sosa:resultTime rdfs:comment "The result time is the instant of time when the Observation, Actuation or Sampling activity was completed."@en ;
 rdfs:range xsd:dateTime .
```
```turtle
:startedAtTime rdfs:comment "The time at which an activity started. See also prov:endedAtTime."@en ;
    rdfs:domain :Activity ;
    rdfs:range xsd:dateTime  .
```
```turtle
:endedAtTime rdfs:comment "The time at which an activity ended. See also prov:startedAtTime."@en ;
    rdfs:domain :Activity ;
    rdfs:range xsd:dateTime .
```
 sosa:resultTime is een  prov:endedAtTime, sosa:Actuation, sosa:Sampling en sosa:Observation zijn een prov:Activity
```turtle
sosa:resultTime  rdfs:subPropertyOf prov:endedAtTime .

sosa:Actuation rdfs:subClassOf prov:Activity  .
sosa:Sampling rdfs:subClassOf prov:Activity .
sosa:Observation rdfs:subClassOf prov:Activity .
```

2. Een tijdsaanduiding die _**niet noodzakelijk**_ samenvalt met het moment van de activiteit (observatie, actuatie of sampling), maar iets zegt over hetgeen geobserveerd werd. (misschien een fenomeen uit een ver geologisch verleden of een voorspelling in de toekomst cfr. https://www.w3.org/TR/vocab-ssn/#forecasts) In dat geval kunnen er allerlei tijdsaanduidingen gebruikt worden die rdfs:Class (instances) zijn. 

```turtle
sosa:phenomenonTime rdfs:comment "The time that the Result of an Observation, Actuation or Sampling applies to the FeatureOfInterest. Not necessarily the same as the resultTime. May be an Interval or an Instant, or some other compound TemporalEntity."@en ;
  schema:rangeIncludes time:TemporalEntity .
```
### Conclusie:
**_In het geval een tijdsaanduiding wel samenvalt met het moment van de activiteit en er is geen functionele reden om hiervan af te wijken, gebruiken we bij voorkeur xsd:dateTime notaties_** en proberen we periodes uit te drukken met een start en einddatum (vanwege ons favoriete principe, het KISS_principle). (deze beiden kunnen eventueel gekwalificeerd worden, indien meer duiding nodig is, met een klasse prov:Start en prov:End instance.) 
### Referenties:

- http://www.w3.org/ns/sosa/
- http://www.w3.org/ns/sosa/prov/
- https://www.w3.org/ns/prov-o
- https://en.wikipedia.org/wiki/KISS_principle

**Comment by pheyvaer** [comment]
@gezever Als ik het goed begrijp willen we het dus in het AP houden zoals het nu is met prov:startedAtTime en prov:endedAtTime?

**Comment by gezever** [comment]
Ik denk het wel @pheyvaer
